---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rnyokccnfy/xendaro-trade.it.com/
    - /bin/cp -r . $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan route:clear
    - cd $DEPLOYPATH && php artisan view:clear
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan storage:link
